###
GET http://localhost:3000/disorder/read HTTP/1.1
Content-Type: appllication/json


###
POST http://localhost:3000/disorder/create HTTP/1.1
Content-Type: application/json

{
    "name": "autismo",
    "cid": "10"
}

###
PUT http://localhost:3000/disorder/update/1 HTTP/1.1
Content-Type: appllication/json

{
    "name": "depressao"
}

###
DELETE http://localhost:3000/disorder/del/0 HTTP/1.1
Content-Type: appllication/json

