###
GET http://localhost:3000/disorder/read HTTP/1.1
Content-Type: appllication/json


###
POST http://localhost:3000/disorder/create HTTP/1.1
Content-Type: application/json

{
    "title": "autismo",
    "cid": "10",
    "content": "O quê é autismo?"
}

###
POST http://localhost:3000/disorder/create HTTP/1.1
Content-Type: application/json

{
    "title": "bipolaridade",
    "cid": "10",
    "content": "a"
}

###
POST http://localhost:3000/disorder/create HTTP/1.1
Content-Type: application/json

{
    "title": "depressão",
    "cid": "10",
    "content": "a"
}

###
POST http://localhost:3000/disorder/create HTTP/1.1
Content-Type: application/json

{
    "title": "dependência alcolica",
    "cid": "10",
    "content": "a"
}

###
POST http://localhost:3000/disorder/create HTTP/1.1
Content-Type: application/json

{
    "title": "borderline",
    "cid": "10",
    "content": "a"
}

###
POST http://localhost:3000/disorder/create HTTP/1.1
Content-Type: application/json

{
    "title": "Dependência de Drogas Ilicitas ",
    "cid": "10",
    "content": "a"
}

###
POST http://localhost:3000/disorder/create HTTP/1.1
Content-Type: application/json

{
    "title": "Dependencia de Medicamentos",
    "cid": "10",
    "content": "a"
}

###
POST http://localhost:3000/disorder/create HTTP/1.1
Content-Type: application/json

{
    "title": "depressão",
    "cid": "10",
    "content": "a"
}







###
PUT http://localhost:3000/disorder/update/6 HTTP/1.1
Content-Type: application/json

{
    "title": "esquizofrenia",
    "cid": "10",
    "content": "a"
}

###
DELETE http://localhost:3000/disorder/del/4 HTTP/1.1
Content-Type: appllication/json

